/**
 * OnChain API
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CurveAccountDTO from '../model/CurveAccountDTO';
import CurveAddLiquidityEventDTO from '../model/CurveAddLiquidityEventDTO';
import CurveAdminFeeChangeLogDTO from '../model/CurveAdminFeeChangeLogDTO';
import CurveAmplificationCoeffChangeLogDTO from '../model/CurveAmplificationCoeffChangeLogDTO';
import CurveCoinDTO from '../model/CurveCoinDTO';
import CurveContractDTO from '../model/CurveContractDTO';
import CurveContractVersionDTO from '../model/CurveContractVersionDTO';
import CurveDailyVolumeDTO from '../model/CurveDailyVolumeDTO';
import CurveExchangeDTO from '../model/CurveExchangeDTO';
import CurveFeeChangeLogDTO from '../model/CurveFeeChangeLogDTO';
import CurveGaugeDTO from '../model/CurveGaugeDTO';
import CurveGaugeDepositDTO from '../model/CurveGaugeDepositDTO';
import CurveGaugeLiquidityDTO from '../model/CurveGaugeLiquidityDTO';
import CurveGaugeTotalWeightDTO from '../model/CurveGaugeTotalWeightDTO';
import CurveGaugeTypeDTO from '../model/CurveGaugeTypeDTO';
import CurveGaugeTypeWeightDTO from '../model/CurveGaugeTypeWeightDTO';
import CurveGaugeWeightDTO from '../model/CurveGaugeWeightDTO';
import CurveGaugeWeightVoteDTO from '../model/CurveGaugeWeightVoteDTO';
import CurveGaugeWithdrawDTO from '../model/CurveGaugeWithdrawDTO';
import CurveHourlyVolumeDTO from '../model/CurveHourlyVolumeDTO';
import CurveLpTokenDTO from '../model/CurveLpTokenDTO';
import CurvePoolDTO from '../model/CurvePoolDTO';
import CurveProposalDTO from '../model/CurveProposalDTO';
import CurveProposalVoteDTO from '../model/CurveProposalVoteDTO';
import CurveRemoveLiquidityEventDTO from '../model/CurveRemoveLiquidityEventDTO';
import CurveRemoveLiquidityOneEventDTO from '../model/CurveRemoveLiquidityOneEventDTO';
import CurveSystemStateDTO from '../model/CurveSystemStateDTO';
import CurveTokenDTO from '../model/CurveTokenDTO';
import CurveTransferOwnershipEventDTO from '../model/CurveTransferOwnershipEventDTO';
import CurveUnderlyingCoinDTO from '../model/CurveUnderlyingCoinDTO';
import CurveVotingAppDTO from '../model/CurveVotingAppDTO';
import CurveWeeklyVolumeDTO from '../model/CurveWeeklyVolumeDTO';

/**
* Curve service.
* @module api/CurveApi
* @version v1
*/
export default class CurveApi {

    /**
    * Constructs a new CurveApi. 
    * @alias module:api/CurveApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the curveGetAccountsHistorical operation.
     * @callback module:api/CurveApi~curveGetAccountsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveAccountDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Accounts (historical) 🔥
     * Gets accounts.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.address 
     * @param {module:api/CurveApi~curveGetAccountsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveAccountDTO>}
     */
    curveGetAccountsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveAccountDTO];
      return this.apiClient.callApi(
        '/dapps/curve/accounts/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetAddLiquidityEventsHistorical operation.
     * @callback module:api/CurveApi~curveGetAddLiquidityEventsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveAddLiquidityEventDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AddLiquidityEvents (historical) 🔥
     * Gets addliquidityevents.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetAddLiquidityEventsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveAddLiquidityEventDTO>}
     */
    curveGetAddLiquidityEventsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveAddLiquidityEventDTO];
      return this.apiClient.callApi(
        '/dapps/curve/addliquidityevents/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetAdminFeeChangeLogsHistorical operation.
     * @callback module:api/CurveApi~curveGetAdminFeeChangeLogsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveAdminFeeChangeLogDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AdminFeeChangeLogs (historical) 🔥
     * Gets adminfeechangelogs.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetAdminFeeChangeLogsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveAdminFeeChangeLogDTO>}
     */
    curveGetAdminFeeChangeLogsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveAdminFeeChangeLogDTO];
      return this.apiClient.callApi(
        '/dapps/curve/adminfeechangelogs/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetAmplificationCoeffChangeLogsHistorical operation.
     * @callback module:api/CurveApi~curveGetAmplificationCoeffChangeLogsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveAmplificationCoeffChangeLogDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AmplificationCoeffChangeLogs (historical) 🔥
     * Gets amplificationcoeffchangelogs.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetAmplificationCoeffChangeLogsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveAmplificationCoeffChangeLogDTO>}
     */
    curveGetAmplificationCoeffChangeLogsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveAmplificationCoeffChangeLogDTO];
      return this.apiClient.callApi(
        '/dapps/curve/amplificationcoeffchangelogs/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetCoinsHistorical operation.
     * @callback module:api/CurveApi~curveGetCoinsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveCoinDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Coins (historical) 🔥
     * Gets coins.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock 
     * @param {Number} opts.endBlock 
     * @param {Date} opts.startDate 
     * @param {Date} opts.endDate 
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetCoinsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveCoinDTO>}
     */
    curveGetCoinsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveCoinDTO];
      return this.apiClient.callApi(
        '/dapps/curve/coins/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetContractVersionsHistorical operation.
     * @callback module:api/CurveApi~curveGetContractVersionsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveContractVersionDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ContractVersions (historical) 🔥
     * Gets contractversions.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.address 
     * @param {module:api/CurveApi~curveGetContractVersionsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveContractVersionDTO>}
     */
    curveGetContractVersionsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveContractVersionDTO];
      return this.apiClient.callApi(
        '/dapps/curve/contractversions/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetContractsHistorical operation.
     * @callback module:api/CurveApi~curveGetContractsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveContractDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Contracts (historical) 🔥
     * Gets contracts.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetContractsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveContractDTO>}
     */
    curveGetContractsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveContractDTO];
      return this.apiClient.callApi(
        '/dapps/curve/contracts/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetDailyVolumesHistorical operation.
     * @callback module:api/CurveApi~curveGetDailyVolumesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveDailyVolumeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * DailyVolumes (historical) 🔥
     * Gets dailyvolumes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetDailyVolumesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveDailyVolumeDTO>}
     */
    curveGetDailyVolumesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveDailyVolumeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/dailyvolumes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetExchangesHistorical operation.
     * @callback module:api/CurveApi~curveGetExchangesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveExchangeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Exchanges (historical) 🔥
     * Gets exchanges.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetExchangesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveExchangeDTO>}
     */
    curveGetExchangesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveExchangeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/exchanges/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetFeeChangeLogsHistorical operation.
     * @callback module:api/CurveApi~curveGetFeeChangeLogsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveFeeChangeLogDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * FeeChangeLogs (historical) 🔥
     * Gets feechangelogs.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetFeeChangeLogsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveFeeChangeLogDTO>}
     */
    curveGetFeeChangeLogsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveFeeChangeLogDTO];
      return this.apiClient.callApi(
        '/dapps/curve/feechangelogs/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeDepositsHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeDepositsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeDepositDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeDeposits (historical) 🔥
     * Gets gaugedeposits.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetGaugeDepositsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeDepositDTO>}
     */
    curveGetGaugeDepositsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeDepositDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugedeposits/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeLiquiditysHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeLiquiditysHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeLiquidityDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeLiquiditys (historical) 🔥
     * Gets gaugeliquiditys.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.user 
     * @param {module:api/CurveApi~curveGetGaugeLiquiditysHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeLiquidityDTO>}
     */
    curveGetGaugeLiquiditysHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'user': opts['user']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeLiquidityDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugeliquiditys/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeTotalWeightsHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeTotalWeightsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeTotalWeightDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeTotalWeights (historical) 🔥
     * Gets gaugetotalweights.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetGaugeTotalWeightsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeTotalWeightDTO>}
     */
    curveGetGaugeTotalWeightsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeTotalWeightDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugetotalweights/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeTypeWeightsHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeTypeWeightsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeTypeWeightDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeTypeWeights (historical) 🔥
     * Gets gaugetypeweights.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetGaugeTypeWeightsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeTypeWeightDTO>}
     */
    curveGetGaugeTypeWeightsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeTypeWeightDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugetypeweights/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeTypesHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeTypesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeTypeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeTypes (historical) 🔥
     * Gets gaugetypes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.name 
     * @param {module:api/CurveApi~curveGetGaugeTypesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeTypeDTO>}
     */
    curveGetGaugeTypesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'name': opts['name']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeTypeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugetypes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeWeightVotesHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeWeightVotesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeWeightVoteDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeWeightVotes (historical) 🔥
     * Gets gaugeweightvotes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.user 
     * @param {module:api/CurveApi~curveGetGaugeWeightVotesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeWeightVoteDTO>}
     */
    curveGetGaugeWeightVotesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'user': opts['user']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeWeightVoteDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugeweightvotes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeWeightsHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeWeightsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeWeightDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeWeights (historical) 🔥
     * Gets gaugeweights.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetGaugeWeightsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeWeightDTO>}
     */
    curveGetGaugeWeightsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeWeightDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugeweights/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugeWithdrawsHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugeWithdrawsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeWithdrawDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GaugeWithdraws (historical) 🔥
     * Gets gaugewithdraws.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetGaugeWithdrawsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeWithdrawDTO>}
     */
    curveGetGaugeWithdrawsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeWithdrawDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gaugewithdraws/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetGaugesHistorical operation.
     * @callback module:api/CurveApi~curveGetGaugesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveGaugeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gauges (historical) 🔥
     * Gets gauges.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.address 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetGaugesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveGaugeDTO>}
     */
    curveGetGaugesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveGaugeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/gauges/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetHourlyVolumesHistorical operation.
     * @callback module:api/CurveApi~curveGetHourlyVolumesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveHourlyVolumeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HourlyVolumes (historical) 🔥
     * Gets hourlyvolumes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetHourlyVolumesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveHourlyVolumeDTO>}
     */
    curveGetHourlyVolumesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveHourlyVolumeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/hourlyvolumes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetLpTokensHistorical operation.
     * @callback module:api/CurveApi~curveGetLpTokensHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveLpTokenDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * LpTokens (historical) 🔥
     * Gets lptokens.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.address 
     * @param {String} opts.name 
     * @param {String} opts.symbol 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetLpTokensHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveLpTokenDTO>}
     */
    curveGetLpTokensHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address'],
        'name': opts['name'],
        'symbol': opts['symbol'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveLpTokenDTO];
      return this.apiClient.callApi(
        '/dapps/curve/lptokens/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetPoolsHistorical operation.
     * @callback module:api/CurveApi~curveGetPoolsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurvePoolDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pools (historical) 🔥
     * Gets pools.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id Pool address.
     * @param {String} opts.name Pool's human-readable name.
     * @param {module:api/CurveApi~curveGetPoolsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurvePoolDTO>}
     */
    curveGetPoolsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'name': opts['name']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurvePoolDTO];
      return this.apiClient.callApi(
        '/dapps/curve/pools/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetProposalVotesHistorical operation.
     * @callback module:api/CurveApi~curveGetProposalVotesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveProposalVoteDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ProposalVotes (historical) 🔥
     * Gets proposalvotes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetProposalVotesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveProposalVoteDTO>}
     */
    curveGetProposalVotesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveProposalVoteDTO];
      return this.apiClient.callApi(
        '/dapps/curve/proposalvotes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetProposalsHistorical operation.
     * @callback module:api/CurveApi~curveGetProposalsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveProposalDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Proposals (historical) 🔥
     * Gets proposals.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {module:api/CurveApi~curveGetProposalsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveProposalDTO>}
     */
    curveGetProposalsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveProposalDTO];
      return this.apiClient.callApi(
        '/dapps/curve/proposals/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetRemoveLiquidityEventsHistorical operation.
     * @callback module:api/CurveApi~curveGetRemoveLiquidityEventsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveRemoveLiquidityEventDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * RemoveLiquidityEvents (historical) 🔥
     * Gets removeliquidityevents.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetRemoveLiquidityEventsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveRemoveLiquidityEventDTO>}
     */
    curveGetRemoveLiquidityEventsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveRemoveLiquidityEventDTO];
      return this.apiClient.callApi(
        '/dapps/curve/removeliquidityevents/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetRemoveLiquidityOneEventsHistorical operation.
     * @callback module:api/CurveApi~curveGetRemoveLiquidityOneEventsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveRemoveLiquidityOneEventDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * RemoveLiquidityOneEvents (historical) 🔥
     * Gets removeliquidityoneevents.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetRemoveLiquidityOneEventsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveRemoveLiquidityOneEventDTO>}
     */
    curveGetRemoveLiquidityOneEventsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveRemoveLiquidityOneEventDTO];
      return this.apiClient.callApi(
        '/dapps/curve/removeliquidityoneevents/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetSystemStatesHistorical operation.
     * @callback module:api/CurveApi~curveGetSystemStatesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveSystemStateDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * SystemStates (historical) 🔥
     * Gets systemstates.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id Singleton ID, equals to 'current'.
     * @param {module:api/CurveApi~curveGetSystemStatesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveSystemStateDTO>}
     */
    curveGetSystemStatesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveSystemStateDTO];
      return this.apiClient.callApi(
        '/dapps/curve/systemstates/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetTokensHistorical operation.
     * @callback module:api/CurveApi~curveGetTokensHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveTokenDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Tokens (historical) 🔥
     * Gets tokens.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.address 
     * @param {String} opts.name 
     * @param {String} opts.symbol 
     * @param {module:api/CurveApi~curveGetTokensHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveTokenDTO>}
     */
    curveGetTokensHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address'],
        'name': opts['name'],
        'symbol': opts['symbol']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveTokenDTO];
      return this.apiClient.callApi(
        '/dapps/curve/tokens/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetTransferOwnershipEventsHistorical operation.
     * @callback module:api/CurveApi~curveGetTransferOwnershipEventsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveTransferOwnershipEventDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * TransferOwnershipEvents (historical) 🔥
     * Gets transferownershipevents.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetTransferOwnershipEventsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveTransferOwnershipEventDTO>}
     */
    curveGetTransferOwnershipEventsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveTransferOwnershipEventDTO];
      return this.apiClient.callApi(
        '/dapps/curve/transferownershipevents/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetUnderlyingCoinsHistorical operation.
     * @callback module:api/CurveApi~curveGetUnderlyingCoinsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveUnderlyingCoinDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * UnderlyingCoins (historical) 🔥
     * Gets underlyingcoins.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock 
     * @param {Number} opts.endBlock 
     * @param {Date} opts.startDate 
     * @param {Date} opts.endDate 
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetUnderlyingCoinsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveUnderlyingCoinDTO>}
     */
    curveGetUnderlyingCoinsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveUnderlyingCoinDTO];
      return this.apiClient.callApi(
        '/dapps/curve/underlyingcoins/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetVotingAppsHistorical operation.
     * @callback module:api/CurveApi~curveGetVotingAppsHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveVotingAppDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VotingApps (historical) 🔥
     * Gets votingapps.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id App address.
     * @param {String} opts.address 
     * @param {module:api/CurveApi~curveGetVotingAppsHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveVotingAppDTO>}
     */
    curveGetVotingAppsHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'address': opts['address']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveVotingAppDTO];
      return this.apiClient.callApi(
        '/dapps/curve/votingapps/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the curveGetWeeklyVolumesHistorical operation.
     * @callback module:api/CurveApi~curveGetWeeklyVolumesHistoricalCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CurveWeeklyVolumeDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * WeeklyVolumes (historical) 🔥
     * Gets weeklyvolumes.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.startBlock The start block. If endblock is not given, only those entities will be included that were exactly created in startBlock.
     * @param {Number} opts.endBlock The end block. Useful to filter data in range of blocks (FROM startBlock TO endBlock).
     * @param {Date} opts.startDate The start date of timeframe. If endDate is not given, entities created FROM startDate TO startDate plus 24 hours will be included.
     * @param {Date} opts.endDate The end date of timeframe.
     * @param {String} opts.id 
     * @param {String} opts.pool 
     * @param {module:api/CurveApi~curveGetWeeklyVolumesHistoricalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CurveWeeklyVolumeDTO>}
     */
    curveGetWeeklyVolumesHistorical(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'startBlock': opts['startBlock'],
        'endBlock': opts['endBlock'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'id': opts['id'],
        'pool': opts['pool']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [CurveWeeklyVolumeDTO];
      return this.apiClient.callApi(
        '/dapps/curve/weeklyvolumes/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
