# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_SWAPS_CURRENT = "/chains/{chain_id}/dapps/sushiswap/swaps/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_BUNDLE_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/bundle/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_BUNDLES_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/bundles/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_BURNS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/burns/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_BURNS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/burns/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_FACTORY_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/factory/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_FACTORY_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/factory/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_MINTS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/mints/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_MINTS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/mints/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POI_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/poi/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOL_DAY_DATA_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/poolDayData/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOL_HOUR_DATA_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/poolHourData/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOLS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/pools/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_POOLS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv2/pools/historical"
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_POOLS_HISTORICAL = "/chains/{chain_id}/dapps/sushiswap/pools/historical"
    CHAINS_CHAIN_ID_DAPPS_CURVE_POOLS_HISTORICAL = "/chains/{chain_id}/dapps/curve/pools/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOLS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/pools/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_POOLS_CURRENT = "/chains/{chain_id}/dapps/uniswapv2/pools/current"
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_POOLS_CURRENT = "/chains/{chain_id}/dapps/sushiswap/pools/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOLS_DAY_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/poolsDayData/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POOLS_HOUR_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/poolsHourData/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POSITIONS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/positions/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POSITION_SNAPSHOT_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/positionSnapshot/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_POSITION_SNAPSHOTS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/positionSnapshots/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_SWAPS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/swaps/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_SWAPS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv2/swaps/historical"
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_SWAPS_HISTORICAL = "/chains/{chain_id}/dapps/sushiswap/swaps/historical"
    CHAINS_CHAIN_ID_DAPPS_CURVE_SWAPS_HISTORICAL = "/chains/{chain_id}/dapps/curve/swaps/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_SWAPS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/swaps/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_SWAPS_CURRENT = "/chains/{chain_id}/dapps/uniswapv2/swaps/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TICKS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/ticks/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TICKS_DAY_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/ticksDayData/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv3/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/uniswapv2/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/sushiswap/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_DEX_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/dex/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_CURVE_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/curve/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_COW_TOKENS_HISTORICAL = "/chains/{chain_id}/dapps/cow/tokens/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TOKENS_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/tokens/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV2_TOKENS_CURRENT = "/chains/{chain_id}/dapps/uniswapv2/tokens/current"
    CHAINS_CHAIN_ID_DAPPS_SUSHISWAP_TOKENS_CURRENT = "/chains/{chain_id}/dapps/sushiswap/tokens/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TOKENS_DAY_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/tokensDayData/current"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_TOKENS_HOUR_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/tokensHourData/current"
    CHAINS_CHAIN_ID_DAPPS_DEX_TRADES_HISTORICAL = "/chains/{chain_id}/dapps/dex/trades/historical"
    CHAINS_CHAIN_ID_DAPPS_COW_TRADES_HISTORICAL = "/chains/{chain_id}/dapps/cow/trades/historical"
    CHAINS_CHAIN_ID_DAPPS_UNISWAPV3_UNISWAP_DAY_DATA_CURRENT = "/chains/{chain_id}/dapps/uniswapv3/uniswapDayData/current"
