export * from './accountsApi';
import { AccountsApi } from './accountsApi';
export * from './addLiquidityEventApi';
import { AddLiquidityEventApi } from './addLiquidityEventApi';
export * from './adminFeeChangeLogApi';
import { AdminFeeChangeLogApi } from './adminFeeChangeLogApi';
export * from './amplificationCoeffChangeLogApi';
import { AmplificationCoeffChangeLogApi } from './amplificationCoeffChangeLogApi';
export * from './batchApi';
import { BatchApi } from './batchApi';
export * from './bundlesApi';
import { BundlesApi } from './bundlesApi';
export * from './burnsApi';
import { BurnsApi } from './burnsApi';
export * from './coinsApi';
import { CoinsApi } from './coinsApi';
export * from './contractsApi';
import { ContractsApi } from './contractsApi';
export * from './contractsVersionApi';
import { ContractsVersionApi } from './contractsVersionApi';
export * from './dailyVolumeApi';
import { DailyVolumeApi } from './dailyVolumeApi';
export * from './dayDataApi';
import { DayDataApi } from './dayDataApi';
export * from './depositApi';
import { DepositApi } from './depositApi';
export * from './factoryApi';
import { FactoryApi } from './factoryApi';
export * from './feeChangeLogApi';
import { FeeChangeLogApi } from './feeChangeLogApi';
export * from './gaugeApi';
import { GaugeApi } from './gaugeApi';
export * from './gaugeDepositApi';
import { GaugeDepositApi } from './gaugeDepositApi';
export * from './gaugeLiquidityApi';
import { GaugeLiquidityApi } from './gaugeLiquidityApi';
export * from './gaugeTotalWeightApi';
import { GaugeTotalWeightApi } from './gaugeTotalWeightApi';
export * from './gaugeTypeApi';
import { GaugeTypeApi } from './gaugeTypeApi';
export * from './gaugeTypeWeightApi';
import { GaugeTypeWeightApi } from './gaugeTypeWeightApi';
export * from './gaugeWeightApi';
import { GaugeWeightApi } from './gaugeWeightApi';
export * from './gaugeWeightVoteApi';
import { GaugeWeightVoteApi } from './gaugeWeightVoteApi';
export * from './gaugeWithdrawApi';
import { GaugeWithdrawApi } from './gaugeWithdrawApi';
export * from './hourDataApi';
import { HourDataApi } from './hourDataApi';
export * from './hourlyVolumeApi';
import { HourlyVolumeApi } from './hourlyVolumeApi';
export * from './liquidityPositionApi';
import { LiquidityPositionApi } from './liquidityPositionApi';
export * from './liquidityPositionSnapshotsApi';
import { LiquidityPositionSnapshotsApi } from './liquidityPositionSnapshotsApi';
export * from './lpTokenApi';
import { LpTokenApi } from './lpTokenApi';
export * from './mintsApi';
import { MintsApi } from './mintsApi';
export * from './ordersApi';
import { OrdersApi } from './ordersApi';
export * from './poiApi';
import { PoiApi } from './poiApi';
export * from './poolDayDataApi';
import { PoolDayDataApi } from './poolDayDataApi';
export * from './poolHourDataApi';
import { PoolHourDataApi } from './poolHourDataApi';
export * from './poolsApi';
import { PoolsApi } from './poolsApi';
export * from './positionSnapshotApi';
import { PositionSnapshotApi } from './positionSnapshotApi';
export * from './positionsApi';
import { PositionsApi } from './positionsApi';
export * from './pricesApi';
import { PricesApi } from './pricesApi';
export * from './proposalsApi';
import { ProposalsApi } from './proposalsApi';
export * from './proposalsVoteApi';
import { ProposalsVoteApi } from './proposalsVoteApi';
export * from './removeLiquidityEventApi';
import { RemoveLiquidityEventApi } from './removeLiquidityEventApi';
export * from './removeLiquidityOneEventApi';
import { RemoveLiquidityOneEventApi } from './removeLiquidityOneEventApi';
export * from './settlementApi';
import { SettlementApi } from './settlementApi';
export * from './solutionApi';
import { SolutionApi } from './solutionApi';
export * from './statsApi';
import { StatsApi } from './statsApi';
export * from './sushiswapApi';
import { SushiswapApi } from './sushiswapApi';
export * from './swapsApi';
import { SwapsApi } from './swapsApi';
export * from './systemStateApi';
import { SystemStateApi } from './systemStateApi';
export * from './tickDayDataApi';
import { TickDayDataApi } from './tickDayDataApi';
export * from './ticksApi';
import { TicksApi } from './ticksApi';
export * from './tokenDayDataApi';
import { TokenDayDataApi } from './tokenDayDataApi';
export * from './tokenHourDataApi';
import { TokenHourDataApi } from './tokenHourDataApi';
export * from './tokensApi';
import { TokensApi } from './tokensApi';
export * from './tradesApi';
import { TradesApi } from './tradesApi';
export * from './transactionsApi';
import { TransactionsApi } from './transactionsApi';
export * from './transferOwnershipEventApi';
import { TransferOwnershipEventApi } from './transferOwnershipEventApi';
export * from './underlyingCoinApi';
import { UnderlyingCoinApi } from './underlyingCoinApi';
export * from './uniswapDayDataApi';
import { UniswapDayDataApi } from './uniswapDayDataApi';
export * from './uniswapV2Api';
import { UniswapV2Api } from './uniswapV2Api';
export * from './uniswapV3Api';
import { UniswapV3Api } from './uniswapV3Api';
export * from './usersApi';
import { UsersApi } from './usersApi';
export * from './votingAppApi';
import { VotingAppApi } from './votingAppApi';
export * from './weeklyVolumeApi';
import { WeeklyVolumeApi } from './weeklyVolumeApi';
export * from './withdrawApi';
import { WithdrawApi } from './withdrawApi';
export * from './withdrawRequestApi';
import { WithdrawRequestApi } from './withdrawRequestApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [AccountsApi, AddLiquidityEventApi, AdminFeeChangeLogApi, AmplificationCoeffChangeLogApi, BatchApi, BundlesApi, BurnsApi, CoinsApi, ContractsApi, ContractsVersionApi, DailyVolumeApi, DayDataApi, DepositApi, FactoryApi, FeeChangeLogApi, GaugeApi, GaugeDepositApi, GaugeLiquidityApi, GaugeTotalWeightApi, GaugeTypeApi, GaugeTypeWeightApi, GaugeWeightApi, GaugeWeightVoteApi, GaugeWithdrawApi, HourDataApi, HourlyVolumeApi, LiquidityPositionApi, LiquidityPositionSnapshotsApi, LpTokenApi, MintsApi, OrdersApi, PoiApi, PoolDayDataApi, PoolHourDataApi, PoolsApi, PositionSnapshotApi, PositionsApi, PricesApi, ProposalsApi, ProposalsVoteApi, RemoveLiquidityEventApi, RemoveLiquidityOneEventApi, SettlementApi, SolutionApi, StatsApi, SushiswapApi, SwapsApi, SystemStateApi, TickDayDataApi, TicksApi, TokenDayDataApi, TokenHourDataApi, TokensApi, TradesApi, TransactionsApi, TransferOwnershipEventApi, UnderlyingCoinApi, UniswapDayDataApi, UniswapV2Api, UniswapV3Api, UsersApi, VotingAppApi, WeeklyVolumeApi, WithdrawApi, WithdrawRequestApi];
