=begin comment

OnChain API

 This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             

The version of the OpenAPI document: v1
Contact: support@coinapi.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SushiswapApi');

my $api = WWW::OpenAPIClient::SushiswapApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SushiswapApi');

#
# curve_get_exchanges__current test
#
# uncomment below and update the test
#my $curve_get_exchanges__current_result = $api->curve_get_exchanges__current();

#
# dex_get_trades__current test
#
# uncomment below and update the test
#my $dex_get_trades__current_result = $api->dex_get_trades__current();

#
# sushiswap_get_pools__current test
#
# uncomment below and update the test
#my $sushiswap_get_pools__current_result = $api->sushiswap_get_pools__current();

#
# sushiswap_get_swaps__current test
#
# uncomment below and update the test
#my $sushiswap_get_swaps__current_result = $api->sushiswap_get_swaps__current();

#
# sushiswap_get_tokens__current test
#
# uncomment below and update the test
#my $sushiswap_get_tokens__current_result = $api->sushiswap_get_tokens__current();

