{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import OnChain.Model
import OnChain.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy CowOrderDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CowSettlementDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CowTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CowTradeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CowUserDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveAccountDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveAddLiquidityEventDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveAdminFeeChangeLogDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveAmplificationCoeffChangeLogDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveCoinDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveContractDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveContractVersionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveDailyVolumeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveExchangeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveFeeChangeLogDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeLiquidityDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeTotalWeightDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeTypeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeTypeWeightDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeWeightDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeWeightVoteDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveGaugeWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveHourlyVolumeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveLpTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurvePoolDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveProposalDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveProposalVoteDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveRemoveLiquidityEventDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveRemoveLiquidityOneEventDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveSystemStateDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveTransferOwnershipEventDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveUnderlyingCoinDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveVotingAppDTO)
      propMimeEq MimeJSON (Proxy :: Proxy CurveWeeklyVolumeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexBatchDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexDepositDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexOrderDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexPriceDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexSolutionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexStatsDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexTradeDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexUserDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexWithdrawDTO)
      propMimeEq MimeJSON (Proxy :: Proxy DexWithdrawRequestDTO)
      propMimeEq MimeJSON (Proxy :: Proxy NumericsBigInteger)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapBundleDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapBurnDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapDayDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapFactoryDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapHourDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapLiquidityPositionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapLiquidityPositionSnapshotDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapMintDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapPairDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapPairDayDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapPairHourDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapSwapDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapTokenDayDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapTransactionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy SushiswapUserDTO)
      propMimeEq MimeJSON (Proxy :: Proxy TransactionsETradeAggressiveSide)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2BundleV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2BurnV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2LiquidityPositionSnapshotV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2LiquidityPositionV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2MintV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2PairDayDataV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2PairHourDataV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2PairV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2SwapV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2TokenDayDataV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2TokenV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2TransactionV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2UniswapDayDataV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2UniswapFactoryV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV2UserV2DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3BundleV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3BurnV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3FactoryV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3MintV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3PoolDayDataV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3PoolHourDataV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3PoolV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3PositionSnapshotV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3PositionV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3SwapV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TickDayDataV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TickV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TokenHourDataV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TokenV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TokenV3DayDataDTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3TransactionV3DTO)
      propMimeEq MimeJSON (Proxy :: Proxy UniswapV3UniswapDayDataV3DTO)
      
