export * from './BundlesApi';
import { BundlesApi } from './BundlesApi';
export * from './BurnsApi';
import { BurnsApi } from './BurnsApi';
export * from './FactoryApi';
import { FactoryApi } from './FactoryApi';
export * from './LiquidityPositionApi';
import { LiquidityPositionApi } from './LiquidityPositionApi';
export * from './LiquidityPositionSnapshotsApi';
import { LiquidityPositionSnapshotsApi } from './LiquidityPositionSnapshotsApi';
export * from './MintApi';
import { MintApi } from './MintApi';
export * from './MintsApi';
import { MintsApi } from './MintsApi';
export * from './PoiApi';
import { PoiApi } from './PoiApi';
export * from './PoolDayDataApi';
import { PoolDayDataApi } from './PoolDayDataApi';
export * from './PoolHourDataApi';
import { PoolHourDataApi } from './PoolHourDataApi';
export * from './PoolsApi';
import { PoolsApi } from './PoolsApi';
export * from './PositionSnapshotApi';
import { PositionSnapshotApi } from './PositionSnapshotApi';
export * from './PositionsApi';
import { PositionsApi } from './PositionsApi';
export * from './SushiswapApi';
import { SushiswapApi } from './SushiswapApi';
export * from './SwapsApi';
import { SwapsApi } from './SwapsApi';
export * from './TickDayDataApi';
import { TickDayDataApi } from './TickDayDataApi';
export * from './TicksApi';
import { TicksApi } from './TicksApi';
export * from './TokenDayDataApi';
import { TokenDayDataApi } from './TokenDayDataApi';
export * from './TokenHourDataApi';
import { TokenHourDataApi } from './TokenHourDataApi';
export * from './TokensApi';
import { TokensApi } from './TokensApi';
export * from './TradesApi';
import { TradesApi } from './TradesApi';
export * from './TransactionsApi';
import { TransactionsApi } from './TransactionsApi';
export * from './UniswapDayDataApi';
import { UniswapDayDataApi } from './UniswapDayDataApi';
export * from './UniswapV2Api';
import { UniswapV2Api } from './UniswapV2Api';
export * from './UniswapV3Api';
import { UniswapV3Api } from './UniswapV3Api';
export * from './UserApi';
import { UserApi } from './UserApi';
export const APIS = [BundlesApi, BurnsApi, FactoryApi, LiquidityPositionApi, LiquidityPositionSnapshotsApi, MintApi, MintsApi, PoiApi, PoolDayDataApi, PoolHourDataApi, PoolsApi, PositionSnapshotApi, PositionsApi, SushiswapApi, SwapsApi, TickDayDataApi, TicksApi, TokenDayDataApi, TokenHourDataApi, TokensApi, TradesApi, TransactionsApi, UniswapDayDataApi, UniswapV2Api, UniswapV3Api, UserApi];
