export * from './AccountsApi';
import { AccountsApi } from './AccountsApi';
export * from './AddLiquidityEventApi';
import { AddLiquidityEventApi } from './AddLiquidityEventApi';
export * from './AdminFeeChangeLogApi';
import { AdminFeeChangeLogApi } from './AdminFeeChangeLogApi';
export * from './AmplificationCoeffChangeLogApi';
import { AmplificationCoeffChangeLogApi } from './AmplificationCoeffChangeLogApi';
export * from './BatchApi';
import { BatchApi } from './BatchApi';
export * from './BundlesApi';
import { BundlesApi } from './BundlesApi';
export * from './BurnsApi';
import { BurnsApi } from './BurnsApi';
export * from './CoinsApi';
import { CoinsApi } from './CoinsApi';
export * from './ContractsApi';
import { ContractsApi } from './ContractsApi';
export * from './ContractsVersionApi';
import { ContractsVersionApi } from './ContractsVersionApi';
export * from './DailyVolumeApi';
import { DailyVolumeApi } from './DailyVolumeApi';
export * from './DayDataApi';
import { DayDataApi } from './DayDataApi';
export * from './DepositApi';
import { DepositApi } from './DepositApi';
export * from './FactoryApi';
import { FactoryApi } from './FactoryApi';
export * from './FeeChangeLogApi';
import { FeeChangeLogApi } from './FeeChangeLogApi';
export * from './GaugeApi';
import { GaugeApi } from './GaugeApi';
export * from './GaugeDepositApi';
import { GaugeDepositApi } from './GaugeDepositApi';
export * from './GaugeLiquidityApi';
import { GaugeLiquidityApi } from './GaugeLiquidityApi';
export * from './GaugeTotalWeightApi';
import { GaugeTotalWeightApi } from './GaugeTotalWeightApi';
export * from './GaugeTypeApi';
import { GaugeTypeApi } from './GaugeTypeApi';
export * from './GaugeTypeWeightApi';
import { GaugeTypeWeightApi } from './GaugeTypeWeightApi';
export * from './GaugeWeightApi';
import { GaugeWeightApi } from './GaugeWeightApi';
export * from './GaugeWeightVoteApi';
import { GaugeWeightVoteApi } from './GaugeWeightVoteApi';
export * from './GaugeWithdrawApi';
import { GaugeWithdrawApi } from './GaugeWithdrawApi';
export * from './HourDataApi';
import { HourDataApi } from './HourDataApi';
export * from './HourlyVolumeApi';
import { HourlyVolumeApi } from './HourlyVolumeApi';
export * from './LiquidityPositionApi';
import { LiquidityPositionApi } from './LiquidityPositionApi';
export * from './LiquidityPositionSnapshotsApi';
import { LiquidityPositionSnapshotsApi } from './LiquidityPositionSnapshotsApi';
export * from './LpTokenApi';
import { LpTokenApi } from './LpTokenApi';
export * from './MintsApi';
import { MintsApi } from './MintsApi';
export * from './OrdersApi';
import { OrdersApi } from './OrdersApi';
export * from './PoiApi';
import { PoiApi } from './PoiApi';
export * from './PoolDayDataApi';
import { PoolDayDataApi } from './PoolDayDataApi';
export * from './PoolHourDataApi';
import { PoolHourDataApi } from './PoolHourDataApi';
export * from './PoolsApi';
import { PoolsApi } from './PoolsApi';
export * from './PositionSnapshotApi';
import { PositionSnapshotApi } from './PositionSnapshotApi';
export * from './PositionsApi';
import { PositionsApi } from './PositionsApi';
export * from './PricesApi';
import { PricesApi } from './PricesApi';
export * from './SettlementApi';
import { SettlementApi } from './SettlementApi';
export * from './SolutionApi';
import { SolutionApi } from './SolutionApi';
export * from './StatsApi';
import { StatsApi } from './StatsApi';
export * from './SushiswapApi';
import { SushiswapApi } from './SushiswapApi';
export * from './SwapsApi';
import { SwapsApi } from './SwapsApi';
export * from './TickDayDataApi';
import { TickDayDataApi } from './TickDayDataApi';
export * from './TicksApi';
import { TicksApi } from './TicksApi';
export * from './TokenDayDataApi';
import { TokenDayDataApi } from './TokenDayDataApi';
export * from './TokenHourDataApi';
import { TokenHourDataApi } from './TokenHourDataApi';
export * from './TokensApi';
import { TokensApi } from './TokensApi';
export * from './TradesApi';
import { TradesApi } from './TradesApi';
export * from './TransactionsApi';
import { TransactionsApi } from './TransactionsApi';
export * from './UniswapDayDataApi';
import { UniswapDayDataApi } from './UniswapDayDataApi';
export * from './UniswapV2Api';
import { UniswapV2Api } from './UniswapV2Api';
export * from './UniswapV3Api';
import { UniswapV3Api } from './UniswapV3Api';
export * from './UsersApi';
import { UsersApi } from './UsersApi';
export * from './WithdrawApi';
import { WithdrawApi } from './WithdrawApi';
export * from './WithdrawRequestApi';
import { WithdrawRequestApi } from './WithdrawRequestApi';
export const APIS = [AccountsApi, AddLiquidityEventApi, AdminFeeChangeLogApi, AmplificationCoeffChangeLogApi, BatchApi, BundlesApi, BurnsApi, CoinsApi, ContractsApi, ContractsVersionApi, DailyVolumeApi, DayDataApi, DepositApi, FactoryApi, FeeChangeLogApi, GaugeApi, GaugeDepositApi, GaugeLiquidityApi, GaugeTotalWeightApi, GaugeTypeApi, GaugeTypeWeightApi, GaugeWeightApi, GaugeWeightVoteApi, GaugeWithdrawApi, HourDataApi, HourlyVolumeApi, LiquidityPositionApi, LiquidityPositionSnapshotsApi, LpTokenApi, MintsApi, OrdersApi, PoiApi, PoolDayDataApi, PoolHourDataApi, PoolsApi, PositionSnapshotApi, PositionsApi, PricesApi, SettlementApi, SolutionApi, StatsApi, SushiswapApi, SwapsApi, TickDayDataApi, TicksApi, TokenDayDataApi, TokenHourDataApi, TokensApi, TradesApi, TransactionsApi, UniswapDayDataApi, UniswapV2Api, UniswapV3Api, UsersApi, WithdrawApi, WithdrawRequestApi];
