export * from './CowApi';
import { CowApi } from './CowApi';
export * from './CurveApi';
import { CurveApi } from './CurveApi';
export * from './DexApi';
import { DexApi } from './DexApi';
export * from './SushiswapApi';
import { SushiswapApi } from './SushiswapApi';
export * from './UniswapV2Api';
import { UniswapV2Api } from './UniswapV2Api';
export * from './UniswapV3Api';
import { UniswapV3Api } from './UniswapV3Api';
export const APIS = [CowApi, CurveApi, DexApi, SushiswapApi, UniswapV2Api, UniswapV3Api];
