/*
 * OnChain API
 *
 *  This section will provide necessary information about the `OnChain API` protocol.  <br/><br/> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.                             
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using CoinAPI.EMS.REST.V1.Client;
using CoinAPI.EMS.REST.V1.Api;
using CoinAPI.EMS.REST.V1.Model;

namespace CoinAPI.EMS.REST.V1.Test
{
    /// <summary>
    ///  Class for testing SushiswapApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SushiswapApiTests
    {
        private SushiswapApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SushiswapApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SushiswapApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' SushiswapApi
            //Assert.IsInstanceOf(typeof(SushiswapApi), instance);
        }

        
        /// <summary>
        /// Test CurveGetExchangesCurrent
        /// </summary>
        [Test]
        public void CurveGetExchangesCurrentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CurveGetExchangesCurrent();
            //Assert.IsInstanceOf(typeof(List<CurveExchangeDTO>), response, "response is List<CurveExchangeDTO>");
        }
        
        /// <summary>
        /// Test DexGetTradesCurrent
        /// </summary>
        [Test]
        public void DexGetTradesCurrentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DexGetTradesCurrent();
            //Assert.IsInstanceOf(typeof(List<DexTradeDTO>), response, "response is List<DexTradeDTO>");
        }
        
        /// <summary>
        /// Test SushiswapGetPoolsCurrent
        /// </summary>
        [Test]
        public void SushiswapGetPoolsCurrentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SushiswapGetPoolsCurrent();
            //Assert.IsInstanceOf(typeof(List<SushiswapPairDTO>), response, "response is List<SushiswapPairDTO>");
        }
        
        /// <summary>
        /// Test SushiswapGetSwapsCurrent
        /// </summary>
        [Test]
        public void SushiswapGetSwapsCurrentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SushiswapGetSwapsCurrent();
            //Assert.IsInstanceOf(typeof(List<SushiswapSwapDTO>), response, "response is List<SushiswapSwapDTO>");
        }
        
        /// <summary>
        /// Test SushiswapGetTokensCurrent
        /// </summary>
        [Test]
        public void SushiswapGetTokensCurrentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SushiswapGetTokensCurrent();
            //Assert.IsInstanceOf(typeof(List<SushiswapTokenDTO>), response, "response is List<SushiswapTokenDTO>");
        }
        
    }

}
