-module(openapi_uniswap_v3_swap_dto).

-export([encode/1]).

-export_type([openapi_uniswap_v3_swap_dto/0]).

-type openapi_uniswap_v3_swap_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'vid' => integer(),
       'id' => binary(),
       'transaction' => binary(),
       'timestamp' => openapi_date_time:openapi_date_time(),
       'pool' => binary(),
       'token_0' => binary(),
       'token_1' => binary(),
       'sender' => binary(),
       'recipient' => binary(),
       'origin' => binary(),
       'amount_0' => binary(),
       'amount_1' => binary(),
       'amount_usd' => binary(),
       'sqrt_price_x96' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'tick' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'log_index' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'evaluated_price' => float(),
       'evaluated_amount' => float(),
       'evaluated_aggressor' => openapi_transactions_e_trade_aggressive_side:openapi_transactions_e_trade_aggressive_side(),
       'pool_id' => binary(),
       'transaction_id' => binary()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'vid' := Vid,
          'id' := Id,
          'transaction' := Transaction,
          'timestamp' := Timestamp,
          'pool' := Pool,
          'token_0' := Token0,
          'token_1' := Token1,
          'sender' := Sender,
          'recipient' := Recipient,
          'origin' := Origin,
          'amount_0' := Amount0,
          'amount_1' := Amount1,
          'amount_usd' := AmountUsd,
          'sqrt_price_x96' := SqrtPriceX96,
          'tick' := Tick,
          'log_index' := LogIndex,
          'evaluated_price' := EvaluatedPrice,
          'evaluated_amount' := EvaluatedAmount,
          'evaluated_aggressor' := EvaluatedAggressor,
          'pool_id' := PoolId,
          'transaction_id' := TransactionId
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'vid' => Vid,
       'id' => Id,
       'transaction' => Transaction,
       'timestamp' => Timestamp,
       'pool' => Pool,
       'token_0' => Token0,
       'token_1' => Token1,
       'sender' => Sender,
       'recipient' => Recipient,
       'origin' => Origin,
       'amount_0' => Amount0,
       'amount_1' => Amount1,
       'amount_usd' => AmountUsd,
       'sqrt_price_x96' => SqrtPriceX96,
       'tick' => Tick,
       'log_index' => LogIndex,
       'evaluated_price' => EvaluatedPrice,
       'evaluated_amount' => EvaluatedAmount,
       'evaluated_aggressor' => EvaluatedAggressor,
       'pool_id' => PoolId,
       'transaction_id' => TransactionId
     }.
