-module(openapi_uniswap_v3_pool_hour_data_v3_dto).

-export([encode/1]).

-export_type([openapi_uniswap_v3_pool_hour_data_v3_dto/0]).

-type openapi_uniswap_v3_pool_hour_data_v3_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'id' => binary(),
       'period_start_unix' => integer(),
       'pool' => binary(),
       'liquidity' => binary(),
       'sqrt_price' => binary(),
       'token_0_price' => binary(),
       'token_1_price' => binary(),
       'tick' => binary(),
       'fee_growth_global_0x128' => binary(),
       'fee_growth_global_1x128' => binary(),
       'tvl_usd' => binary(),
       'volume_token_0' => binary(),
       'volume_token_1' => binary(),
       'volume_usd' => binary(),
       'fees_usd' => binary(),
       'tx_count' => binary(),
       'open' => binary(),
       'high' => binary(),
       'low' => binary(),
       'close' => binary(),
       'vid' => integer()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'id' := Id,
          'period_start_unix' := PeriodStartUnix,
          'pool' := Pool,
          'liquidity' := Liquidity,
          'sqrt_price' := SqrtPrice,
          'token_0_price' := Token0Price,
          'token_1_price' := Token1Price,
          'tick' := Tick,
          'fee_growth_global_0x128' := FeeGrowthGlobal0x128,
          'fee_growth_global_1x128' := FeeGrowthGlobal1x128,
          'tvl_usd' := TvlUsd,
          'volume_token_0' := VolumeToken0,
          'volume_token_1' := VolumeToken1,
          'volume_usd' := VolumeUsd,
          'fees_usd' := FeesUsd,
          'tx_count' := TxCount,
          'open' := Open,
          'high' := High,
          'low' := Low,
          'close' := Close,
          'vid' := Vid
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'id' => Id,
       'period_start_unix' => PeriodStartUnix,
       'pool' => Pool,
       'liquidity' => Liquidity,
       'sqrt_price' => SqrtPrice,
       'token_0_price' => Token0Price,
       'token_1_price' => Token1Price,
       'tick' => Tick,
       'fee_growth_global_0x128' => FeeGrowthGlobal0x128,
       'fee_growth_global_1x128' => FeeGrowthGlobal1x128,
       'tvl_usd' => TvlUsd,
       'volume_token_0' => VolumeToken0,
       'volume_token_1' => VolumeToken1,
       'volume_usd' => VolumeUsd,
       'fees_usd' => FeesUsd,
       'tx_count' => TxCount,
       'open' => Open,
       'high' => High,
       'low' => Low,
       'close' => Close,
       'vid' => Vid
     }.
