-module(openapi_uniswap_v3_tick_dto).

-export([encode/1]).

-export_type([openapi_uniswap_v3_tick_dto/0]).

-type openapi_uniswap_v3_tick_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'vid' => integer(),
       'id' => binary(),
       'pool_address' => binary(),
       'tick_idx' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'pool' => binary(),
       'liquidity_gross' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'liquidity_net' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'price_0' => binary(),
       'price_1' => binary(),
       'volume_token_0' => binary(),
       'volume_token_1' => binary(),
       'volume_usd' => binary(),
       'untracked_volume_usd' => binary(),
       'fees_usd' => binary(),
       'collected_fees_token_0' => binary(),
       'collected_fees_token_1' => binary(),
       'collected_fees_usd' => binary(),
       'created_at_timestamp' => openapi_date_time:openapi_date_time(),
       'liquidity_provider_count' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'fee_growth_outside_0x128' => openapi_numerics_big_integer:openapi_numerics_big_integer(),
       'fee_growth_outside_1x128' => openapi_numerics_big_integer:openapi_numerics_big_integer()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'vid' := Vid,
          'id' := Id,
          'pool_address' := PoolAddress,
          'tick_idx' := TickIdx,
          'pool' := Pool,
          'liquidity_gross' := LiquidityGross,
          'liquidity_net' := LiquidityNet,
          'price_0' := Price0,
          'price_1' := Price1,
          'volume_token_0' := VolumeToken0,
          'volume_token_1' := VolumeToken1,
          'volume_usd' := VolumeUsd,
          'untracked_volume_usd' := UntrackedVolumeUsd,
          'fees_usd' := FeesUsd,
          'collected_fees_token_0' := CollectedFeesToken0,
          'collected_fees_token_1' := CollectedFeesToken1,
          'collected_fees_usd' := CollectedFeesUsd,
          'created_at_timestamp' := CreatedAtTimestamp,
          'liquidity_provider_count' := LiquidityProviderCount,
          'fee_growth_outside_0x128' := FeeGrowthOutside0x128,
          'fee_growth_outside_1x128' := FeeGrowthOutside1x128
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'vid' => Vid,
       'id' => Id,
       'pool_address' => PoolAddress,
       'tick_idx' => TickIdx,
       'pool' => Pool,
       'liquidity_gross' => LiquidityGross,
       'liquidity_net' => LiquidityNet,
       'price_0' => Price0,
       'price_1' => Price1,
       'volume_token_0' => VolumeToken0,
       'volume_token_1' => VolumeToken1,
       'volume_usd' => VolumeUsd,
       'untracked_volume_usd' => UntrackedVolumeUsd,
       'fees_usd' => FeesUsd,
       'collected_fees_token_0' => CollectedFeesToken0,
       'collected_fees_token_1' => CollectedFeesToken1,
       'collected_fees_usd' => CollectedFeesUsd,
       'created_at_timestamp' => CreatedAtTimestamp,
       'liquidity_provider_count' => LiquidityProviderCount,
       'fee_growth_outside_0x128' => FeeGrowthOutside0x128,
       'fee_growth_outside_1x128' => FeeGrowthOutside1x128
     }.
