-module(openapi_dex_order_dto).

-export([encode/1]).

-export_type([openapi_dex_order_dto/0]).

-type openapi_dex_order_dto() ::
    #{ 'entry_time' => openapi_date_time:openapi_date_time(),
       'recv_time' => openapi_date_time:openapi_date_time(),
       'block_number' => integer(),
       'id' => binary(),
       'owner' => binary(),
       'order_id' => integer(),
       'from_batch_id' => binary(),
       'from_epoch' => binary(),
       'until_batch_id' => binary(),
       'until_epoch' => binary(),
       'buy_token' => binary(),
       'sell_token' => binary(),
       'price_numerator' => binary(),
       'price_denominator' => binary(),
       'max_sell_amount' => binary(),
       'min_receive_amount' => binary(),
       'sold_volume' => binary(),
       'bought_volume' => binary(),
       'create_epoch' => binary(),
       'cancel_epoch' => binary(),
       'delete_epoch' => binary(),
       'tx_hash' => binary(),
       'tx_log_index' => binary(),
       'vid' => integer()
     }.

encode(#{ 'entry_time' := EntryTime,
          'recv_time' := RecvTime,
          'block_number' := BlockNumber,
          'id' := Id,
          'owner' := Owner,
          'order_id' := OrderId,
          'from_batch_id' := FromBatchId,
          'from_epoch' := FromEpoch,
          'until_batch_id' := UntilBatchId,
          'until_epoch' := UntilEpoch,
          'buy_token' := BuyToken,
          'sell_token' := SellToken,
          'price_numerator' := PriceNumerator,
          'price_denominator' := PriceDenominator,
          'max_sell_amount' := MaxSellAmount,
          'min_receive_amount' := MinReceiveAmount,
          'sold_volume' := SoldVolume,
          'bought_volume' := BoughtVolume,
          'create_epoch' := CreateEpoch,
          'cancel_epoch' := CancelEpoch,
          'delete_epoch' := DeleteEpoch,
          'tx_hash' := TxHash,
          'tx_log_index' := TxLogIndex,
          'vid' := Vid
        }) ->
    #{ 'entry_time' => EntryTime,
       'recv_time' => RecvTime,
       'block_number' => BlockNumber,
       'id' => Id,
       'owner' => Owner,
       'order_id' => OrderId,
       'from_batch_id' => FromBatchId,
       'from_epoch' => FromEpoch,
       'until_batch_id' => UntilBatchId,
       'until_epoch' => UntilEpoch,
       'buy_token' => BuyToken,
       'sell_token' => SellToken,
       'price_numerator' => PriceNumerator,
       'price_denominator' => PriceDenominator,
       'max_sell_amount' => MaxSellAmount,
       'min_receive_amount' => MinReceiveAmount,
       'sold_volume' => SoldVolume,
       'bought_volume' => BoughtVolume,
       'create_epoch' => CreateEpoch,
       'cancel_epoch' => CancelEpoch,
       'delete_epoch' => DeleteEpoch,
       'tx_hash' => TxHash,
       'tx_log_index' => TxLogIndex,
       'vid' => Vid
     }.
