-module(openapi_order_history).

-export([encode/1]).

-export_type([openapi_order_history/0]).

-type openapi_order_history() ::
    #{ 'apikey' => binary(),
       'exchangeId' => binary(),
       'clientOrderId' => binary(),
       'symbolIdExchange' => binary(),
       'symbolIdCoinapi' => binary(),
       'amountOrder' => integer(),
       'price' => integer(),
       'side' => integer(),
       'orderType' => binary(),
       'timeInForce' => binary(),
       'expireTime' => calendar:date(),
       'execInst' => list(),
       'clientOrderIdFormatExchange' => binary(),
       'exchangeOrderId' => binary(),
       'amountOpen' => integer(),
       'amountFilled' => integer(),
       'avgPx' => integer(),
       'status' => binary(),
       'statusHistoryStatus' => list(),
       'statusHistoryTime' => list(),
       'errorMessageResult' => binary(),
       'errorMessageReason' => binary(),
       'errorMessageMessage' => binary(),
       'fillsTime' => list(),
       'fillsPrice' => list(),
       'fillsAmount' => list(),
       'createdTime' => calendar:date()
     }.

encode(#{ 'apikey' := Apikey,
          'exchangeId' := ExchangeId,
          'clientOrderId' := ClientOrderId,
          'symbolIdExchange' := SymbolIdExchange,
          'symbolIdCoinapi' := SymbolIdCoinapi,
          'amountOrder' := AmountOrder,
          'price' := Price,
          'side' := Side,
          'orderType' := OrderType,
          'timeInForce' := TimeInForce,
          'expireTime' := ExpireTime,
          'execInst' := ExecInst,
          'clientOrderIdFormatExchange' := ClientOrderIdFormatExchange,
          'exchangeOrderId' := ExchangeOrderId,
          'amountOpen' := AmountOpen,
          'amountFilled' := AmountFilled,
          'avgPx' := AvgPx,
          'status' := Status,
          'statusHistoryStatus' := StatusHistoryStatus,
          'statusHistoryTime' := StatusHistoryTime,
          'errorMessageResult' := ErrorMessageResult,
          'errorMessageReason' := ErrorMessageReason,
          'errorMessageMessage' := ErrorMessageMessage,
          'fillsTime' := FillsTime,
          'fillsPrice' := FillsPrice,
          'fillsAmount' := FillsAmount,
          'createdTime' := CreatedTime
        }) ->
    #{ 'apikey' => Apikey,
       'exchangeId' => ExchangeId,
       'clientOrderId' => ClientOrderId,
       'symbolIdExchange' => SymbolIdExchange,
       'symbolIdCoinapi' => SymbolIdCoinapi,
       'amountOrder' => AmountOrder,
       'price' => Price,
       'side' => Side,
       'orderType' => OrderType,
       'timeInForce' => TimeInForce,
       'expireTime' => ExpireTime,
       'execInst' => ExecInst,
       'clientOrderIdFormatExchange' => ClientOrderIdFormatExchange,
       'exchangeOrderId' => ExchangeOrderId,
       'amountOpen' => AmountOpen,
       'amountFilled' => AmountFilled,
       'avgPx' => AvgPx,
       'status' => Status,
       'statusHistoryStatus' => StatusHistoryStatus,
       'statusHistoryTime' => StatusHistoryTime,
       'errorMessageResult' => ErrorMessageResult,
       'errorMessageReason' => ErrorMessageReason,
       'errorMessageMessage' => ErrorMessageMessage,
       'fillsTime' => FillsTime,
       'fillsPrice' => FillsPrice,
       'fillsAmount' => FillsAmount,
       'createdTime' => CreatedTime
     }.
